name: lds_agenda

services:
  nextjs:
    container_name: lds_agenda_nextjs
    build:
      context: ./docker
      args:
        - NODE_VERSION=24.12.0 # LTS
    volumes:
      - ".:/home/app"
    ports:
      - "8005:3000"
